allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  '@prisma/engines': true
  prisma: true
  grpc-tools: true
  protobufjs: true
  '@scarf/scarf': true
ignoredBuiltDependencies:
  - '@scarf/scarf'
