export enum FilesErrorCode {
  INVALID_USER_ID = 'INVALID_USER_ID',
  INVALID_IMAGE_COUNT = 'INVALID_IMAGE_COUNT',
  INVALID_IMAGE_SIZE = 'INVALID_IMAGE_SIZE',
  DUPLICATE_CLIENT_FILE_ID = 'DUPLICATE_CLIENT_FILE_ID',
  DUPLICATE_IMAGE_UPLOAD_ID = 'DUPLICATE_IMAGE_UPLOAD_ID',
  IMAGE_UPLOAD_NOT_FOUND = 'IMAGE_UPLOAD_NOT_FOUND',
  INVALID_IMAGE_UPLOAD_STATUS = 'INVALID_IMAGE_UPLOAD_STATUS',
  IMAGE_UPLOAD_METADATA_MISMATCH = 'IMAGE_UPLOAD_METADATA_MISMATCH',
  UNSUPPORTED_IMAGE_CONTENT_TYPE = 'UNSUPPORTED_IMAGE_CONTENT_TYPE',
}

export abstract class FilesError extends Error {
  abstract readonly code: FilesErrorCode;

  protected constructor(message: string) {
    super(message);
    this.name = new.target.name;
  }
}
