apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true # опционально, но хорошая практика
            runAsUser: 1000 # опционально
          ports:
            - containerPort: PORT_CONTAINER
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: DATABASE_URL
            - name: FILES_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_ENDPOINT
            - name: FILES_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_REGION
            - name: FILES_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_BUCKET
            - name: FILES_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_ACCESS_KEY_ID
            - name: FILES_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_SECRET_ACCESS_KEY
            - name: FILES_S3_DOWNLOAD_URL_EXPIRES_IN_SECONDS
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_DOWNLOAD_URL_EXPIRES_IN_SECONDS
            - name: FILES_S3_UPLOAD_URL_EXPIRES_IN_SECONDS
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_S3_UPLOAD_URL_EXPIRES_IN_SECONDS
            - name: FILES_GRPC_URL
              valueFrom:
                secretKeyRef:
                  name: remarkgram-files-production-config-secret
                  key: FILES_GRPC_URL
