// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

config({ path: new URL('.env', import.meta.url) });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['POSTS_DATABASE_URL'],
  },
});
