-- CreateTable
CREATE TABLE "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" VARCHAR NOT NULL,
    "email" VARCHAR NOT NULL,
    "hash" VARCHAR NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL,
    "confirmationIsConfirmed" BOOLEAN NOT NULL,
    "confirmationCode" VARCHAR,
    "confirmationExpiration" TIMESTAMPTZ,
    "passwordRecoveryCode" VARCHAR,
    "passwordRecoveryExpiration" TIMESTAMPTZ,
    "deletedAt" TIMESTAMPTZ,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- AddForeignKey
ALTER TABLE "devices" ADD CONSTRAINT "devices_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
