export enum PaymentsErrorCode {
  INVALID_PAYMENT_METHOD = 'INVALID_PAYMENT_METHOD',
  INVALID_PLAN_ID = 'INVALID_PLAN_ID',
  INVALID_PLAN_PRICE = 'INVALID_PLAN_PRICE',
  INVALID_PLAN_CURRENCY = 'INVALID_PLAN_CURRENCY',
  INVALID_PLAN_PERIOD = 'INVALID_PLAN_PERIOD',
  INVALID_PAYMENT_ID = 'INVALID_PAYMENT_ID',
  INVALID_PAYMENT_REFERENCE = 'INVALID_PAYMENT_REFERENCE',
  INVALID_PAYMENT_AMOUNT = 'INVALID_PAYMENT_AMOUNT',
  INVALID_PAYMENT_CURRENCY = 'INVALID_PAYMENT_CURRENCY',
  INVALID_PAYMENT_PERIOD = 'INVALID_PAYMENT_PERIOD',
  INVALID_PAYMENT_PROVIDER = 'INVALID_PAYMENT_PROVIDER',
  INVALID_PAYMENT_IDEMPOTENT_KEY = 'INVALID_PAYMENT_IDEMPOTENT_KEY',
  INVALID_PAYMENT_SUBSCRIPTION_ID = 'INVALID_PAYMENT_SUBSCRIPTION_ID',
  INVALID_PAYMENT_STATE = 'INVALID_PAYMENT_STATE',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_IDEMPOTENCY_CONFLICT = 'PAYMENT_IDEMPOTENCY_CONFLICT',
  PAYMENT_ACCESS_DENIED = 'PAYMENT_ACCESS_DENIED',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  INVALID_PROVIDER_EVENT = 'INVALID_PROVIDER_EVENT',
}

export abstract class PaymentsError extends Error {
  abstract readonly code: PaymentsErrorCode;
  protected constructor(message: string) {
    super(message);
    this.name = new.target.name;
  }
}
