export enum PostsErrorCode {
  INVALID_USER_ID = 'INVALID_USER_ID',
  INVALID_POST_DESCRIPTION = 'INVALID_POST_DESCRIPTION',
  INVALID_POST_IMAGE_COUNT = 'INVALID_POST_IMAGE_COUNT',
  DUPLICATE_POST_IMAGE_ID = 'DUPLICATE_POST_IMAGE_ID',
  POST_IMAGE_NOT_FOUND = 'POST_IMAGE_NOT_FOUND',
  POST_IMAGES_NOT_AVAILABLE = 'POST_IMAGES_NOT_AVAILABLE',
  POST_IMAGE_ALREADY_ATTACHED = 'POST_IMAGE_ALREADY_ATTACHED',
  IMAGE_UPLOADS_SERVICE_UNAVAILABLE = 'IMAGE_UPLOADS_SERVICE_UNAVAILABLE',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_UPDATE_CONFLICT = 'POST_UPDATE_CONFLICT',
  POST_ACCESS_FORBIDDEN = 'POST_ACCESS_FORBIDDEN',
  INVALID_POST_ID = 'INVALID_POST_ID',
  INVALID_POST_PAGE_LIMIT = 'INVALID_POST_PAGE_LIMIT',
  INVALID_POST_CURSOR = 'INVALID_POST_CURSOR',
}

export abstract class PostsError extends Error {
  abstract readonly code: PostsErrorCode;

  protected constructor(message: string) {
    super(message);
    this.name = new.target.name;
  }
}
