export enum UserAccountsErrorCode {
  INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  USER_ALREADY_LOGGED_IN = 'USER_ALREADY_LOGGED_IN',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  NO_ACTIVE_SESSION = 'NO_ACTIVE_SESSION',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_ACCESS_DENIED = 'SESSION_ACCESS_DENIED',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CONFIRMATION_CODE = 'INVALID_CONFIRMATION_CODE',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  CONFIRMATION_CODE_EXPIRED = 'CONFIRMATION_CODE_EXPIRED',
  INCORRECT_EMAIL = 'INCORRECT_EMAIL',
  INVALID_PASSWORD_RESET_TOKEN = 'INVALID_PASSWORD_RESET_TOKEN',
  OAUTH_EMAIL_REQUIRED = 'OAUTH_EMAIL_REQUIRED',
  OAUTH_EMAIL_NOT_VERIFIED = 'OAUTH_EMAIL_NOT_VERIFIED',
  OAUTH_EMAIL_CONFIRMATION_REQUIRED = 'OAUTH_EMAIL_CONFIRMATION_REQUIRED',
  OAUTH_IDENTITY_OWNER_NOT_FOUND = 'OAUTH_IDENTITY_OWNER_NOT_FOUND',
  OAUTH_SESSION_CREATION_FAILED = 'OAUTH_SESSION_CREATION_FAILED',
  OAUTH_IDENTITY_LINKED_TO_ANOTHER_USER = 'OAUTH_IDENTITY_LINKED_TO_ANOTHER_USER',
  OAUTH_PROVIDER_ALREADY_LINKED = 'OAUTH_PROVIDER_ALREADY_LINKED',
  OAUTH_IDENTITY_CONFLICT = 'OAUTH_IDENTITY_CONFLICT',
}

export abstract class UserAccountsError extends Error {
  abstract readonly code: UserAccountsErrorCode;

  protected constructor(message: string) {
    super(message);
    this.name = new.target.name;
  }
}
