export enum UserAccountsErrorCode {
  INVALID_AVATAR_FILE_ID = 'INVALID_AVATAR_FILE_ID',
  INVALID_IDEMPOTENCY_KEY = 'INVALID_IDEMPOTENCY_KEY',
  AVATAR_UPDATE_CONFLICT = 'AVATAR_UPDATE_CONFLICT',
  AVATAR_IDEMPOTENCY_KEY_CONFLICT = 'AVATAR_IDEMPOTENCY_KEY_CONFLICT',
  AVATAR_FILE_NOT_FOUND = 'AVATAR_FILE_NOT_FOUND',
  AVATAR_FILE_STATE_CONFLICT = 'AVATAR_FILE_STATE_CONFLICT',
  INVALID_AVATAR_IMAGE = 'INVALID_AVATAR_IMAGE',
  AVATAR_FILES_UNAVAILABLE = 'AVATAR_FILES_UNAVAILABLE',

  INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  USER_ALREADY_LOGGED_IN = 'USER_ALREADY_LOGGED_IN',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  NO_ACTIVE_SESSION = 'NO_ACTIVE_SESSION',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_ACCESS_DENIED = 'SESSION_ACCESS_DENIED',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CONFIRMATION_CODE = 'INVALID_CONFIRMATION_CODE',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  CONFIRMATION_CODE_EXPIRED = 'CONFIRMATION_CODE_EXPIRED',
  INCORRECT_EMAIL = 'INCORRECT_EMAIL',
  INVALID_PASSWORD_RESET_TOKEN = 'INVALID_PASSWORD_RESET_TOKEN',
  OAUTH_EMAIL_REQUIRED = 'OAUTH_EMAIL_REQUIRED',
  OAUTH_EMAIL_NOT_VERIFIED = 'OAUTH_EMAIL_NOT_VERIFIED',
  OAUTH_EMAIL_CONFIRMATION_REQUIRED = 'OAUTH_EMAIL_CONFIRMATION_REQUIRED',
  OAUTH_IDENTITY_OWNER_NOT_FOUND = 'OAUTH_IDENTITY_OWNER_NOT_FOUND',
  OAUTH_SESSION_CREATION_FAILED = 'OAUTH_SESSION_CREATION_FAILED',
  OAUTH_IDENTITY_LINKED_TO_ANOTHER_USER = 'OAUTH_IDENTITY_LINKED_TO_ANOTHER_USER',
  OAUTH_PROVIDER_ALREADY_LINKED = 'OAUTH_PROVIDER_ALREADY_LINKED',
  OAUTH_IDENTITY_CONFLICT = 'OAUTH_IDENTITY_CONFLICT',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PERSONAL_INFO_FIRST_NAME = 'INVALID_PERSONAL_INFO_FIRST_NAME',
  INVALID_PERSONAL_INFO_LAST_NAME = 'INVALID_PERSONAL_INFO_LAST_NAME',
  INVALID_BIRTH_DATE_FORMAT = 'INVALID_BIRTH_DATE_FORMAT',
  NON_EXISTENT_CALENDAR_DATE = 'NON_EXISTENT_CALENDAR_DATE',
  BIRTH_DATE_MIN_ALLOWED_AGE = 'BIRTH_DATE_MIN_ALLOWED_AGE',
  INVALID_PERSONAL_INFO_ABOUT_ME = 'INVALID_PERSONAL_INFO_ABOUT_ME',
  INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE',
  INVALID_CITY = 'INVALID_CITY',
  INVALID_USERNAME_PATTERN = 'INVALID_USERNAME_PATTERN',
  INVALID_USERNAME_LENGTH = 'INVALID_USERNAME_LENGTH',
}

export abstract class UserAccountsError extends Error {
  abstract readonly code: UserAccountsErrorCode;

  protected constructor(message: string) {
    super(message);
    this.name = new.target.name;
  }
}
