// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { resolve } from 'node:path';
import { defineConfig, env } from 'prisma/config';

const appDirectory = import.meta.dirname;
const environment = process.env.NODE_ENV ?? 'development';

dotenv.config({
  path: [
    resolve(appDirectory, `.env.${environment}.local`),
    resolve(appDirectory, `.env.${environment}`),
    resolve(appDirectory, '.env'),
  ],
  quiet: true,
});

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'node --experimental-strip-types apps/payments/prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
