-- CreateTable
CREATE TABLE "posts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,

    CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);
