apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           securityContext:
             allowPrivilegeEscalation: false
             runAsNonRoot: true      # опционально, но хорошая практика
             runAsUser: 1000         # опционально
           ports:
             - containerPort: PORT_CONTAINER
           env:
             - name: USER_ACCOUNTS_GRPC_URL
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: USER_ACCOUNTS_GRPC_URL
             - name: JWT_PUBLIC_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: JWT_PUBLIC_KEY
             - name: ENABLE_TESTING_ENDPOINTS
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: ENABLE_TESTING_ENDPOINTS
             - name: TESTING_ENDPOINT_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: TESTING_ENDPOINT_KEY
             - name: GOOGLE_RECAPTCHA_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GOOGLE_RECAPTCHA_SECRET_KEY
             - name: FILES_GRPC_URL
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: FILES_GRPC_URL
             - name: REFRESH_TOKEN_COOKIE_MAX_AGE_MS
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: REFRESH_TOKEN_COOKIE_MAX_AGE_MS
             - name: GATEWAY_PORT
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GATEWAY_PORT
             - name: CORS_ALLOWED_ORIGINS
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: CORS_ALLOWED_ORIGINS
             - name: GOOGLE_OAUTH_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GOOGLE_OAUTH_CLIENT_ID
             - name: GOOGLE_OAUTH_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GOOGLE_OAUTH_CLIENT_SECRET
             - name: GOOGLE_OAUTH_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GOOGLE_OAUTH_CALLBACK_URL
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: GITHUB_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GITHUB_CALLBACK_URL
             - name: GITHUB_API_VERSION
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GITHUB_API_VERSION
             - name: GITHUB_USER_AGENT
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-production-config-secret
                   key: GITHUB_USER_AGENT
