syntax = "proto3";

package remarkgram.files.v1;

service FilesService {
  rpc InitiateImageUploads(InitiateImageUploadsRequest) returns (InitiateImageUploadsResponse);
}

message InitiateImageUploadsRequest {
  string user_id = 1;
  repeated ImageUploadMetadata images = 2;
}

message ImageUploadMetadata {
  string original_filename = 1;
  string content_type = 2;
  int32 size = 3;
  string client_file_id = 4;
}

message InitiateImageUploadsResponse {
  repeated ImageUploadSession sessions = 1;
}

message ImageUploadSession {
  string id = 1;
  string client_file_id = 2;
  string url = 3;
  map<string, string> fields = 4;
}
