syntax = "proto3";

package remarkgram.files.v1;

service FilesService {
  rpc InitiateImageUploads(InitiateImageUploadsRequest) returns (InitiateImageUploadsResponse);
  rpc CompleteImageUploads(CompleteImageUploadsRequest) returns (CompleteImageUploadsResponse);
  rpc ReserveImageUploads(ReserveImageUploadsRequest) returns (ReserveImageUploadsResponse);
  rpc AttachReservedImageUploads(AttachReservedImageUploadsRequest) returns (AttachReservedImageUploadsResponse);
  rpc ReleaseReservedImageUploads(ReleaseReservedImageUploadsRequest) returns (ReleaseReservedImageUploadsResponse);
    rpc GetFileDownloadUrl(GetFileDownloadUrlRequest) returns (GetFileDownloadUrlResponse);
}

service TestingService {
    rpc DeleteAllData(DeleteAllDataRequest) returns (DeleteAllDataResponse);
}

message InitiateImageUploadsRequest {
    string user_id = 1;
    repeated ImageUploadMetadata images = 2;
}

message ImageUploadMetadata {
    string original_filename = 1;
    string content_type = 2;
    int32 size = 3;
    string client_file_id = 4;
}

message InitiateImageUploadsResponse {
    repeated ImageUploadSession sessions = 1;
}

message ImageUploadSession {
    string id = 1;
    string client_file_id = 2;
    string url = 3;
    map<string, string> fields = 4;
}

message CompleteImageUploadsRequest {
    string user_id = 1;
    repeated string upload_ids = 2;
}

message ReserveImageUploadsRequest {
  string user_id = 1;
  repeated string upload_ids = 2;
  string reservation_id = 3;
  string operation_id = 4;
}

message ReleaseReservedImageUploadsRequest {
  string user_id = 1;
  string reservation_id = 2;
  string operation_id = 3;
}

message AttachReservedImageUploadsRequest {
  string user_id = 1;
  string reservation_id = 2;
  string operation_id = 3;
}

message CompleteImageUploadsResponse {}

message DeleteAllDataRequest {}

message DeleteAllDataResponse {}

message ReserveImageUploadsResponse {}

message AttachReservedImageUploadsResponse {}

message ReleaseReservedImageUploadsResponse {}

message GetFileDownloadUrlRequest {
    string file_id = 1;
}

message GetFileDownloadUrlResponse {
    string url = 1;
}
